[package]
name = "snarkvm-circuits-metrics"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Performance metrics for circuits for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-circuits-environment]
path = "../environment"
version = "0.7.5"

[dependencies.snarkvm-circuits-types]
path = "../types"
version = "0.7.5"